## Загрузка данных

### Импорт библиотек

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Чтение исходного csv и первичный просмотр данных

In [2]:
df = pd.read_csv("../data/raw/dream.csv", usecols=list(range(1, 22)), header=0, names=["nick",
                                                                 "age",
                                                                 "sex", 
                                                                 "agreement", 
                                                                 "date",
                                                                 "fall_asleep",
                                                                 "wake_up", 
                                                                 "sleep_quality", 
                                                                 "awakenings", 
                                                                 "dream_remembered", 
                                                                 "dream_colored", 
                                                                 "amount_of_coffee", 
                                                                 "amount_of_coffee_after16",
                                                                 "alcohol",
                                                                 "strong_emotions",
                                                                 "stress_level",
                                                                 "hours_of_physical_activity",
                                                                 "daytime_sleep",
                                                                 "food_before_bed",
                                                                 "screen_time",
                                                                 "screen_before_bed",
                                                                 ])
df.head(5)

,nick,age,sex,agreement,date,fall_asleep,wake_up,sleep_quality,awakenings,dream_remembered,...,amount_of_coffee,amount_of_coffee_after16,alcohol,strong_emotions,stress_level,hours_of_physical_activity,daytime_sleep,food_before_bed,screen_time,screen_before_bed
0,OLKA75,45 лет и более,Женский,Да,13.09.2026,23:30:00,6:45:00,3,3,Да,...,1,0,Да,Нет,4,2,Да,Нет,3,Да
1,Zverskiyponos67,до 18 лет,Женский,Да,13.09.2026,2:00:00,10:00:00,3,1,Нет,...,1,0,Нет,Нет,5,0,Нет,Нет,8,Нет
2,Kreeper,от 18 до 30 лет,Женский,Да,13.09.2026,0:00:00,8:13:00,4,0,Нет,...,0,0,Нет,Нет,2,4,Нет,Нет,8,Да
3,Tukiceja,45 лет и более,Мужской,Да,13.09.2026,23:00:00,6:20:00,3,3,Нет,...,1,0,Да,Нет,2,3,Да,Нет,3,Да
4,TihiyOmut,от 18 до 30 лет,Мужской,Да,13.09.2026,3:00:00,10:25:00,5,0,Да,...,10,4,Да,Да,2,1,Нет,Да,3,Да

Значение столбцов:
- id - ник пользователей
- age - возраст
- sex - пол
- agreement - соглашение на обработку персональных даных
- date - дата заполнения
- fall_asleep - время засыпания
- wake_up - время пробуждения
- sleep_quality - оценка качества сна (1-5)
- awakenings - количество пробуждений ночью (1-10)
- dream_remembered - запомнился ли сон (Да/Нет)
- dream_colored - цвет сна (Цветной/Чёрно-белый/Точно не могу сказать)
- amount_of_coffee - количество чашек кофе (0-10)
- amount_of_coffee_after16 - количество чашек кофе после 16 (0-10)
- alcohol - употребление алкоголя (Да/Нет)
- strong_emotions - сильные эмоции (Да/Нет)
- stress_level - уровень стресса (1-10)
- hours_of_physical_activity - часы физической активности (0-10)
- daytime_sleep - сон днём (Да/Нет)
- food_before_bed - еда перед сном (Да/Нет)
- screen_time - экранное время за день (0-10)
- screen_before_bed - экран перед сном (Да/Нет)

Два дополнительных признака были исключены из основной версии датасета, поскольку они были добавлены после начала сбора, имеют значительную долю пропусков. Их влияние не исследуется в рамках данной версии проекта.

In [3]:
print(f"Размер dataframe: {df.shape}")

Размер dataframe: (420, 21)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   nick                        420 non-null    str
 1   age                         420 non-null    str
 2   sex                         420 non-null    str
 3   agreement                   420 non-null    str
 4   date                        420 non-null    str
 5   fall_asleep                 420 non-null    str
 6   wake_up                     420 non-null    str
 7   sleep_quality               420 non-null    int64
 8   awakenings                  420 non-null    int64
 9   dream_remembered            420 non-null    str
 10  dream_colored               187 non-null    str
 11  amount_of_coffee            420 non-null    int64
 12  amount_of_coffee_after16    420 non-null    int64
 13  alcohol                     420 non-null    str
 14  strong_emotions             420 non-null    str
 15  stress_level                420 non-null    int64
 16  hours_of_physical_activity  420 non-null    int64
 17  daytime_sleep               420 non-null    str
 18  food_before_bed             420 non-null    str
 19  screen_time                 420 non-null    int64
 20  screen_before_bed           420 non-null    str
dtypes: int64(7), str(14)
memory usage: 69.0 KB

Все категориальные значения были предварительно ограничены вариантами Google Forms. На этапе контроля проверено, что после импорта присутствуют только ожидаемые категории.

In [5]:
df.isna().sum()

nick                            0
age                             0
sex                             0
agreement                       0
date                            0
fall_asleep                     0
wake_up                         0
sleep_quality                   0
awakenings                      0
dream_remembered                0
dream_colored                 233
amount_of_coffee                0
amount_of_coffee_after16        0
alcohol                         0
strong_emotions                 0
stress_level                    0
hours_of_physical_activity      0
daytime_sleep                   0
food_before_bed                 0
screen_time                     0
screen_before_bed               0
dtype: int64

In [6]:
df.describe()

,sleep_quality,awakenings,amount_of_coffee,amount_of_coffee_after16,stress_level,hours_of_physical_activity,screen_time
count,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000
mean,3.745238,1.257143,0.790476,0.264286,3.633333,2.530952,5.533333
std,1.070031,1.639481,1.119966,0.569018,2.297416,1.995578,2.694701
min,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,0.000000,0.000000,2.000000,1.000000,3.000000
50%,4.000000,1.000000,0.000000,0.000000,3.000000,2.000000,5.000000
75%,5.000000,2.000000,1.000000,0.000000,5.000000,4.000000,8.000000
max,5.000000,10.000000,10.000000,4.000000,10.000000,10.000000,10.000000

В ряде количественных признаков среднее значение превышает медиану, что может указывать на правостороннюю асимметрию распределения. Некоторые экстремальные значения требуют дополнительной проверки.

In [7]:
# Дубликаты
df.duplicated().sum()

np.int64(0)

На стадии проверки качества данных дупликаты не были обнаружены

In [8]:
# Уникальные значения
df.nunique()

nick                           53
age                             4
sex                             2
agreement                       1
date                           14
fall_asleep                   117
wake_up                       118
sleep_quality                   5
awakenings                     11
dream_remembered                2
dream_colored                   3
amount_of_coffee                6
amount_of_coffee_after16        4
alcohol                         2
strong_emotions                 2
stress_level                   10
hours_of_physical_activity     10
daytime_sleep                   2
food_before_bed                 2
screen_time                    11
screen_before_bed               2
dtype: int64

In [9]:
# Сохранение csv файла
df.to_csv("../data/processed/primary_dream.csv", index=False)