## Загрузка данных

### Импорт библиотек

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Чтение исходного csv и первичный просмотр данных

In [2]:
df = pd.read_csv("../data/raw/dream.csv")
df.head(5)

,Отметка времени,"Придумайте себе анонимный псевдоним, который будешь указывать на протяжении всего исследования.\r\nНапример: WHITE27.",Укажите свой возраст,Укажите свой пол,Я соглашаюсь на обработку моих персональных данных,Какое сегодня число?,Время засыпания,Время пробуждения,Оцените качество сна,Сколько раз вы просыпались ночью?,...,Употребляли ли вы алкоголь вчера?,Испытывали ли вы сильные эмоции вчера?,Оцените свой уровень стресса вчера,Сколько в среднем часов вы вчера потратили на физическую активность?,Спали ли вы днём вчера?,Принимали ли вы пищу менее чем за 2 часа до сна?,Сколько времени вчера вы провели перед экраном?,"Пользовались ли вы смартфоном, компьютером или другим экраном в течение последнего часа перед сном?",Просыпались ли вы ночью и не могли заснуть?,"Если ваш ответ на прошлый вопрос «Да», то сколько часов вы бодрствовали? (Если «Нет» пропускаете этот вопрос)"
0,13.09.2026 9:44:56,OLKA75,45 лет и более,Женский,Да,13.09.2026,23:30:00,6:45:00,3,3,...,Да,Нет,4,2,Да,Нет,3,Да,NaN,NaN
1,13.09.2026 10:28:51,Zverskiyponos67,до 18 лет,Женский,Да,13.09.2026,2:00:00,10:00:00,3,1,...,Нет,Нет,5,0,Нет,Нет,8,Нет,NaN,NaN
2,13.09.2026 10:42:32,Kreeper,от 18 до 30 лет,Женский,Да,13.09.2026,0:00:00,8:13:00,4,0,...,Нет,Нет,2,4,Нет,Нет,8,Да,NaN,NaN
3,13.09.2026 10:51:44,Tukiceja,45 лет и более,Мужской,Да,13.09.2026,23:00:00,6:20:00,3,3,...,Да,Нет,2,3,Да,Нет,3,Да,NaN,NaN
4,13.09.2026 11:04:45,TihiyOmut,от 18 до 30 лет,Мужской,Да,13.09.2026,3:00:00,10:25:00,5,0,...,Да,Да,2,1,Нет,Да,3,Да,NaN,NaN

In [3]:
print(f"Размер dataframe: {df.shape}")

Размер dataframe: (420, 24)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 24 columns):
 #   Column                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                               --------------  -----
 0   Отметка времени                                                                                                      420 non-null    str
 1   Придумайте себе анонимный псевдоним, который будешь указывать на протяжении всего исследования.
Например: WHITE27.  420 non-null    str
 2   Укажите свой возраст                                                                                                 420 non-null    str
 3   Укажите свой пол                                                                                                     420 non-null    str
 4   Я соглашаюсь на обработку моих персональных данных                                                                   420 non-null    str
 5   Какое сегодня число?                                                                                                 420 non-null    str
 6   Время засыпания                                                                                                      420 non-null    str
 7   Время пробуждения                                                                                                    420 non-null    str
 8   Оцените качество сна                                                                                                 420 non-null    int64
 9   Сколько раз вы просыпались ночью?                                                                                    420 non-null    int64
 10  Запомнили ли вы сегодня какое-либо сновидение?                                                                       420 non-null    str
 11   Какого цвета было сновидение?                                                                                       187 non-null    str
 12  Сколько порций кофе/энергетиков вы употребляли вчера                                                                 420 non-null    int64
 13  Сколько порций кофе/энергетиков вы выпили после 16:00                                                                420 non-null    int64
 14  Употребляли ли вы алкоголь вчера?                                                                                    420 non-null    str
 15  Испытывали ли вы сильные эмоции вчера?                                                                               420 non-null    str
 16  Оцените свой уровень стресса вчера                                                                                   420 non-null    int64
 17  Сколько в среднем часов вы вчера потратили на физическую активность?                                                 420 non-null    int64
 18  Спали ли вы днём вчера?                                                                                              420 non-null    str
 19  Принимали ли вы пищу менее чем за 2 часа до сна?                                                                     420 non-null    str
 20  Сколько времени вчера вы провели перед экраном?                                                                      420 non-null    int64
 21  Пользовались ли вы смартфоном, компьютером или другим экраном в течение последнего часа перед сном?                  420 non-null    str
 22  Просыпались ли вы ночью и не могли заснуть?                                                                          301 non-null    str
 23  Если ваш ответ на прошлый вопрос «Да», то сколько часов вы бодрствовали? (Если «Нет» пропускаете этот вопрос)        54 non-null     str
dtypes: int64(7), str(17)
memory usage: 78.9 KB

In [5]:
df.isna().sum()

Отметка времени                                                                                                            0
Придумайте себе анонимный псевдоним, который будешь указывать на протяжении всего исследования.\r\nНапример: WHITE27.      0
Укажите свой возраст                                                                                                       0
Укажите свой пол                                                                                                           0
Я соглашаюсь на обработку моих персональных данных                                                                         0
Какое сегодня число?                                                                                                       0
Время засыпания                                                                                                            0
Время пробуждения                                                                                                          0
Оцените качество сна                                                                                                       0
Сколько раз вы просыпались ночью?                                                                                          0
Запомнили ли вы сегодня какое-либо сновидение?                                                                             0
 Какого цвета было сновидение?                                                                                           233
Сколько порций кофе/энергетиков вы употребляли вчера                                                                       0
Сколько порций кофе/энергетиков вы выпили после 16:00                                                                      0
Употребляли ли вы алкоголь вчера?                                                                                          0
Испытывали ли вы сильные эмоции вчера?                                                                                     0
Оцените свой уровень стресса вчера                                                                                         0
Сколько в среднем часов вы вчера потратили на физическую активность?                                                       0
Спали ли вы днём вчера?                                                                                                    0
Принимали ли вы пищу менее чем за 2 часа до сна?                                                                           0
Сколько времени вчера вы провели перед экраном?                                                                            0
Пользовались ли вы смартфоном, компьютером или другим экраном в течение последнего часа перед сном?                        0
Просыпались ли вы ночью и не могли заснуть?                                                                              119
Если ваш ответ на прошлый вопрос «Да», то сколько часов вы бодрствовали? (Если «Нет» пропускаете этот вопрос)            366
dtype: int64

In [6]:
df.describe()

,Оцените качество сна,Сколько раз вы просыпались ночью?,Сколько порций кофе/энергетиков вы употребляли вчера,Сколько порций кофе/энергетиков вы выпили после 16:00,Оцените свой уровень стресса вчера,Сколько в среднем часов вы вчера потратили на физическую активность?,Сколько времени вчера вы провели перед экраном?
count,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000
mean,3.745238,1.257143,0.790476,0.264286,3.633333,2.530952,5.533333
std,1.070031,1.639481,1.119966,0.569018,2.297416,1.995578,2.694701
min,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,0.000000,0.000000,0.000000,2.000000,1.000000,3.000000
50%,4.000000,1.000000,0.000000,0.000000,3.000000,2.000000,5.000000
75%,5.000000,2.000000,1.000000,0.000000,5.000000,4.000000,8.000000
max,5.000000,10.000000,10.000000,4.000000,10.000000,10.000000,10.000000

В ряде количественных признаков среднее значение превышает медиану, что может указывать на правостороннюю асимметрию распределения. Некоторые экстремальные значения требуют дополнительной проверки.

In [7]:
# Дубликаты
df.duplicated().sum()

np.int64(0)

На стадии проверки качества данных дупликаты не были обнаружены

In [8]:
# Уникальные значения
df.nunique()

Отметка времени                                                                                                          419
Придумайте себе анонимный псевдоним, который будешь указывать на протяжении всего исследования.\r\nНапример: WHITE27.     53
Укажите свой возраст                                                                                                       4
Укажите свой пол                                                                                                           2
Я соглашаюсь на обработку моих персональных данных                                                                         1
Какое сегодня число?                                                                                                      14
Время засыпания                                                                                                          117
Время пробуждения                                                                                                        118
Оцените качество сна                                                                                                       5
Сколько раз вы просыпались ночью?                                                                                         11
Запомнили ли вы сегодня какое-либо сновидение?                                                                             2
 Какого цвета было сновидение?                                                                                             3
Сколько порций кофе/энергетиков вы употребляли вчера                                                                       6
Сколько порций кофе/энергетиков вы выпили после 16:00                                                                      4
Употребляли ли вы алкоголь вчера?                                                                                          2
Испытывали ли вы сильные эмоции вчера?                                                                                     2
Оцените свой уровень стресса вчера                                                                                        10
Сколько в среднем часов вы вчера потратили на физическую активность?                                                      10
Спали ли вы днём вчера?                                                                                                    2
Принимали ли вы пищу менее чем за 2 часа до сна?                                                                           2
Сколько времени вчера вы провели перед экраном?                                                                           11
Пользовались ли вы смартфоном, компьютером или другим экраном в течение последнего часа перед сном?                        2
Просыпались ли вы ночью и не могли заснуть?                                                                                2
Если ваш ответ на прошлый вопрос «Да», то сколько часов вы бодрствовали? (Если «Нет» пропускаете этот вопрос)              4
dtype: int64